jobs:
  - name: runSh_0_n
    type: runSh
    steps:
      - TASK:
        - script: secs=6; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
        - script: echo "versionName=random0_$BUILD_NUMBER" >> $JOB_STATE/runSh_0_n.env

  - name: runSh_1_n
    type: runSh
    steps:
      - TASK:
        - script: secs=6; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
        - script: shipctl post_resource_state runSh_1_n versionName random1_$BUILD_NUMBER

  - name: runSh_2_n
    type: runSh
    steps:
      - IN: runSh_0_n
        dependencyMode: strict 
      - IN: runSh_1_n
      - TASK:
        - script: secs=6; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done

  - name: runSh_3_n
    type: runSh
    steps:
      - IN: runSh_0_n
        dependencyMode: immediate 
      - IN: runSh_1_n
      - TASK:
        - script: secs=6; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done

  - name: runSh_4_n
    type: runSh
    steps:
      - IN: runSh_0_n
        dependencyMode: chrono 
      - IN: runSh_1_n    
      - TASK:
        - script: secs=6; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
        
  - name: job-1
    type: runSh
    steps:    
      - TASK:
        - script: failing it   
        
  - name: job-2
    type: runSh
    steps:
      - TASK:
        - script: secs=120; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done 
        
  - name: job-3
    type: runSh
    steps:
      - TASK:
        - script: secs=120; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done 
        
  - name: job-4
    type: runSh
    dependencyMode: strict
    steps:
      - IN: job-1
      - IN: resource-1
      - IN: job-2
      - TASK:
        - script: secs=60; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done 
        
   
  - name: job-5
    type: runSh
    dependencyMode: strict    
    steps:
      - IN: job-2
      - IN: resource-1
      - IN: job-3    
      - TASK:
        - script: secs=60; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done    

  - name: job-6
    type: runSh   
    steps:
      - IN: job-4
      - TASK:
        - script: secs=60; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done 

  - name: job-7
    type: runSh   
    steps:
      - IN: job-5
      - TASK:
        - script: secs=60; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done 

resources:
  - name: resource-1
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.10
