jobs:
  - name: raw-manifest
    type: manifest
    steps:
      - IN: package-raw-file

  - name: man-prod9
    type: manifest
    steps:
      - IN: nginx-prod9
      - TASK: managed

  - name: man-prod10
    type: manifest
    steps:
      - IN: nginx-prod10
      - IN: replicas
      - IN: params
      - IN: dockerOptions      
      - TASK: managed

  - name: azure
    type: deploy
    steps:
      - IN: man-prod9      
      - IN: azure-cluster
      - TASK: managed
        deployMethod: blueGreen
    flags:
      - azure

  - name: cluster
    type: deploy
    steps:
      - IN: raw-manifest    
      - IN: node-cluster
      - TASK: managed
    flags:
      - cluster

#  - name: ddc
#    type: deploy
#    steps:
#      - IN: man-prod9  
#      - IN: man-prod10
#        switch: off      
#      - IN: ddc-cluster
#      - TASK: managed
#        deployMethod: blueGreen
#    flags:
#      - ddc

  - name: dcl
    type: deploy
    steps:
      - IN: man-prod9  
      - IN: man-prod10
        switch: off
      - IN: dcl-cluster
      - TASK: managed
        deployMethod: scale
    flags:
      - dcl

  - name: ecs
    type: deploy
    steps:
      - IN: man-prod9  
      - IN: man-prod10
        switch: off      
      - IN: ecs-cluster
      - TASK: managed
        deployMethod: blueGreen
    flags:
      - ecs 

  - name: gke
    type: deploy
    steps:
      - IN: man-prod9  
      - IN: man-prod10
        switch: off      
      - IN: gke-cluster
      - TASK: managed
        deployMethod: blueGreen
    flags:
      - gke 

  - name: kubernetes
    type: deploy
    steps:
      - IN: man-prod9  
      - IN: man-prod10
        switch: off      
      - IN: kubernetes-cluster
      - TASK: managed
        deployMethod: blueGreen
    flags:
      - kubernetes 

  - name: triton
    type: deploy
    steps:
      - IN: man-prod9  
      - IN: man-prod10
        switch: off      
      - IN: triton-cluster
      - TASK: managed
        deployMethod: blueGreen
    flags:
      - triton 

resources:
  - name: nginx-prod10
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.10

  - name: nginx-prod9
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.9

  - name: replicas
    type: replicas
    version:
      count: 1

  - name: params
    type: params
    version:
      params:
        API_URL: https://localhost:3000
        WWW_URL: https://localhost:8080

  - name: dockerOptions
    type: dockerOptions
    version:
      portMappings:
        - "80:80/tcp"

  - name: package-raw-file
    type: file
    pointer:
      sourceName: https://raw.githubusercontent.com/shippableSamples/sample_pipelines/master/shippable.resources.yml
    seed:
      versionName: initial

  - name: azure-cluster
    type: cluster
    integration: azure-subint

  - name: node-cluster
    type: cluster
    integration: node-subint

  - name: ddc-cluster
    type: cluster
    integration: "ddc-subint"
    pointer:
      sourceName: "ddc-cluster"
      
  - name: dcl-cluster
    type: cluster
    integration: "dcl-subint"
    pointer:
      sourceName: "dcl-cluster"      
      
  - name: ecs-cluster
    type: cluster
    integration: "ecs-subint"
    pointer:
      sourceName: "ecs-cluster"
      region: us-west-2

  - name: gke-cluster
    type: cluster
    integration: "gke-subint"
    pointer:
      sourceName: "gke-cluster"
      region: us-west1-a

  - name: kubernetes-cluster
    type: cluster
    integration: "kube-subint"

  - name: triton-cluster
    type: cluster
    integration: "triton-subint"
    pointer:
      region: us-east-1
