jobs:
  - name: nginx-manifest-1
    type: manifest
    steps:
      - IN: serial-trigger
    flags:
      - manifests 

  - name: sample-runSh
    type: runSh
    architecture: x86_64
    os: Ubuntu_16.04
    steps:
      - IN: dv-scaler
      - TASK:
        - script: sleep 180
        - script: docker images | grep busybox
    flags:
      - runSh 

  - name: runSh-Job
    type: runSh
    steps:
      - IN: nginx-manifest-1
      - TASK:
        - script: sudo apt-get install tree
        - script: tree -F IN
        - script: sleep 3
    on_success:
      - script: echo "successfully completed"
      

  - name: runSh-Job-2
    type: runSh
    steps:
      - IN: nginx-manifest-1
      - TASK:
        - script: sudo apt-get install tree
        - script: tree -F IN
        - script: sleep 3
    on_success:
      - script: echo "successfully completed"      
