jobs:
  - name: test-pipeline
    runtime: 
      os: WindowsServer_2016
      architecture: x86_64
      container: false
    type: runSh
    steps:
      - TASK: 
          script:
            - dir
            - echo "hello"
