jobs:
  - name: myRunSh
    type: runSh
    steps:
      - IN: nginx-image
      - TASK:
        - boot:
             imageName: trriplejay/simpleserver
             imageTag: master.58
             pull: true               #optional
             options: -m 1g      #optional
        - script: docker ps -a    
        - script: ls -al $MYREPO_STATE
      - OUT: myImage
      
  - name: runSh_1
    type: runSh
    allowPublicAccess: true
    steps:
      - IN: nginx-image
      - TASK:
        - script: sleep 60
        
  - name: runSh_2
    type: runSh
    steps:
      - IN: runSh_1
      - TASK:
        - script: sleep 1

  - name: runSh_3
    type: runSh
    steps:
      - IN: runSh_2
      - TASK:
        - script: sleep 1   
        
  - name: runSh_4
    type: runSh
    steps:
      - IN: runSh_3
      - TASK:
        - script: sleep 1
        
  - name: runSh_5
    type: runSh
    steps:
      - TASK:
        - script: sleep 1           
        
  - name: runSh_6
    type: runSh
    steps:
      - IN: runSh_5
      - TASK:
        - script: sleep 1
        
  - name: runSh_7
    type: runSh
    steps:
      - IN: runSh_6
      - TASK:
        - script: sleep 1  
        
  - name: runSh_8
    type: runSh
    steps:
      - TASK:
        - script: sleep 1    
        
  - name: runSh_9
    type: runSh
    steps:
      - IN: runSh_8
      - TASK:
        - script: sleep 1     
        
  - name: runSh_10
    type: runSh
    steps:
      - TASK:
        - script: sleep 1  
        
  - name: runSh_11
    type: runSh
    steps:
      - IN: runSh_4
      - IN: runSh_7 
      - TASK:
        - script: sleep 55
        - script: echo versionName=hello_$BUILD_NUMBER > $JOB_STATE/runSh_11.env
    flags: 
      - random_one
