jobs:
  - name: nginx-manifest-1
    type: manifest
    steps:
      - IN: serial-trigger
    flags:
      - manifests 

  - name: sample-runSh
    type: runSh
    architecture: aarch64
    os: Ubuntu_16.04
    steps:
      - IN: dv-scaler
      - TASK:
        - script: docker images | grep busybox
    flags:
      - runSh 

#  - name: runSh-Job
#    type: runSh
#    steps:
#      - IN: nginx-manifest-1
#      - TASK:
#        - script: sudo apt-get install tree
#        - script: tree -F IN
#        - script: sleep 300
#    on_success:
#      - script: echo "successfully completed"
#      - NOTIFY: hipchat-notifications
