jobs:
  - name: nginx-manifest-1
    type: manifest
    steps:
      - IN: serial-trigger
      - IN: nginx-image-prod81

  - name: runSh-Job
    type: runSh
    steps:
      - IN: nginx-manifest-1
      - TASK:
        - script: sudo apt-get install tree
        - script: tree -F IN
        - script: sleep 300
    on_success:
      - script: echo "successfully completed"
      - NOTIFY: hipchat-notifications
