jobs:
  - name: job-1
    type: runSh
    steps:
      - TASK:
        - script: secs=60; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
        - script: echo "versionName=random1_$BUILD_NUMBER" >> $JOB_STATE/job-1.env
        - script: failing it
    flags:
      - dependenyMode_test

  - name: job-2
    type: runSh
    steps:
      - TASK:
        - script: secs=0; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
        - script: shipctl post_resource_state job-2 versionName random2_$BUILD_NUMBER
    flags:
      - dependenyMode_test        
        
  - name: job-3
    type: runSh
    steps:
      - TASK:
        - script: secs=120; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
        - script: shipctl post_resource_state job-3 versionName random3_$BUILD_NUMBER   
    flags:
      - dependenyMode_test

  - name: strict-Job
    type: runSh
    dependencyMode: strict
    steps:
      - IN: job-2
      - IN: job-3
      - TASK:
        - script: echo "DONE!"
    flags:
      - dependenyMode_test

  - name: immediate-Job
    type: runSh
    dependencyMode: immediate
    steps:
      - IN: job-1
      - IN: job-2
      - IN: job-3
      - TASK:
        - script: echo "DONE!"
    flags:
      - dependenyMode_test

  - name: chrono-Job
    type: runSh
    dependencyMode: chrono
    steps:
      - IN: job-2
      - IN: job-3
      - TASK:
        - script: echo "DONE!"      
    flags:
      - dependenyMode_test
