jobs:
  - name: man-prod9
    type: manifest
    steps:
      - IN: nginx-prod9
      - TASK: managed

  - name: man-prod10
    type: manifest
    steps:
      - IN: nginx-prod10
      - IN: replicas
      - IN: params
      - IN: dockerOptions      
      - TASK: managed

  - name: ddc
    type: deploy
    steps:
      - IN: man-prod9  
      - IN: man-prod10
      - IN: ddc-cluster
      - TASK: managed
    flags:
      - ddc
