jobs:
  - name: tag_push_ecr
    type: runSh
    steps:
      - TASK:
        - script: echo "done"
        
  - name: tag_push_repo
    type: runSh
    steps:
      - TASK:
        - script: echo "done"  

  - name: tag_push_ubuntu_14
    type: runSh
    steps:
      - TASK:
        - script: echo "done"
        
  - name: tag_push_ubuntu_16
    type: runSh
    steps:
      - TASK:
        - script: echo "done"  

  - name: build_ami_stable
    type: runSh
    steps:
      - IN: tag_push_ecr
      - IN: tag_push_repo
      - IN: tag_push_ubuntu_14
      - IN: tag_push_ubuntu_16
      - TASK:
        - script: echo "done"

  - name: build_ami_unstable
    type: runSh
    steps:
      - IN: tag_push_ecr
      - IN: tag_push_repo
      - IN: tag_push_ubuntu_14
      - IN: tag_push_ubuntu_16
      - TASK:
        - script: echo "done"

  - name: build_ami_5.3.2
    type: runSh
    steps:
      - IN: tag_push_ecr
      - IN: tag_push_repo
      - IN: tag_push_ubuntu_14
      - IN: tag_push_ubuntu_16
      - TASK:
        - script: echo "done"

  - name: build_ami_5.4.1
    type: runSh
    steps:
      - IN: tag_push_ecr
      - IN: tag_push_repo
      - IN: tag_push_ubuntu_14
      - IN: tag_push_ubuntu_16
      - TASK:
        - script: echo "done"

  - name: build_ami_5.8.2
    type: runSh
    steps:
      - IN: tag_push_ecr
      - IN: tag_push_repo
      - IN: tag_push_ubuntu_14
      - IN: tag_push_ubuntu_16
      - TASK:
        - script: echo "done"
  
  - name: build_ami_5.10.4
    type: runSh
    steps:
      - IN: tag_push_ecr
      - IN: tag_push_repo
      - IN: tag_push_ubuntu_14
      - IN: tag_push_ubuntu_16
      - TASK:
        - script: echo "done"
