jobs:
  - name: tag_push_ecr
    type: runSh
    steps:
      - TASK:
        - script: echo "done"
        
  - name: tag_push_repo
    type: runSh
    steps:
      - TASK:
        - script: echo "done"  

  - name: tag_push_ubuntu_14
    type: runSh
    steps:
      - TASK:
        - script: echo "done"
        
  - name: tag_push_ubuntu_16
    type: runSh
    steps:
      - TASK:
        - script: echo "done"  

  - name: build_ami_stable
    type: runSh
    steps:
      - IN: tag_push_ecr
      - IN: tag_push_repo
      - IN: tag_push_ubuntu_14
      - IN: tag_push_ubuntu_16
      - TASK:
        - script: echo "done"

  - name: build_ami_unstable
    type: runSh
    steps:
      - IN: tag_push_ecr
      - IN: tag_push_repo
      - IN: tag_push_ubuntu_14
      - IN: tag_push_ubuntu_16
      - TASK:
        - script: echo "done"

  - name: build_ami_532
    type: runSh
    steps:
      - IN: tag_push_ecr
      - IN: tag_push_repo
      - IN: tag_push_ubuntu_14
      - IN: tag_push_ubuntu_16
      - TASK:
        - script: echo "done"

  - name: build_ami_541
    type: runSh
    steps:
      - IN: tag_push_ecr
      - IN: tag_push_repo
      - IN: tag_push_ubuntu_14
      - IN: tag_push_ubuntu_16
      - TASK:
        - script: echo "done"

  - name: build_ami_582
    type: runSh
    steps:
      - IN: tag_push_ecr
      - IN: tag_push_repo
      - IN: tag_push_ubuntu_14
      - IN: tag_push_ubuntu_16
      - TASK:
        - script: echo "done"
  
  - name: build_ami_5104
    type: runSh
    steps:
      - IN: tag_push_ecr
      - IN: tag_push_repo
      - IN: tag_push_ubuntu_14
      - IN: tag_push_ubuntu_16
      - TASK:
        - script: echo "done"
