jobs:
  - name: test-pipeline
    type: runSh
    steps:
      - TASK: 
          script:
            - uname -a
            - lsb_release -a
            - which shipctl
            - docker images
            - docker version
