jobs:
  - name: manifest_1
    type: manifest
    steps:
      - IN: nginx_image_10
      
  - name: manifest_2
    type: manifest
    steps:
      - IN: nginx_image_10
      
  - name: manifest_3
    type: manifest
    steps:
      - IN: nginx_image_10
      
  - name: manifest_4
    type: manifest
    steps:
      - IN: nginx_image_10
      
  - name: manifest_5
    type: manifest
    steps:
      - IN: nginx_image_10
      
  - name: manifest_6
    type: manifest
    steps:
      - IN: nginx_image_10
      
  - name: manifest_7
    type: manifest
    steps:
      - IN: nginx_image_10      

  - name: sample_node_runCI
    type: runCI
    steps:
      - IN: manifest_1

  - name: runSh_trigger_2
    type: runSh
    steps:
      - IN: manifest_2
      - TASK:
        - script: sleep 60

  - name: runSh_trigger_3
    type: runSh
    steps:
      - IN: manifest_3
      - TASK:
        - script: sleep 60

  - name: sample_java_runCI
    type: runCI
    dependencyMode: strict
    steps:
      - IN: manifest_4
      - IN: sample_node_runCI
      - IN: runSh_trigger_2
      - IN: runSh_trigger_3
        switch: off
      - IN: manifest_6
      - IN: manifest_7
        switch: off        
      - IN: nginx_image_11
      - IN: random_1

  - name: runSh_main
    type: runSh
    dependencyMode: strict
    steps:
      - IN: manifest_5
      - IN: sample_node_runCI
      - IN: runSh_trigger_2
      - IN: runSh_trigger_3
        switch: off
      - IN: manifest_6
      - IN: manifest_7
        switch: off           
      - IN: nginx_image_12
      - IN: random_2
      - TASK:
        - script: sleep 60
             
  - name: sample_pipelines_runCI
    type: runCI
    dependencyMode: immediate
    steps:
      - IN: manifest_4
      - IN: sample_node_runCI
      - IN: runSh_trigger_2
      - IN: runSh_trigger_3
        switch: off
      - IN: manifest_6
      - IN: manifest_7
        switch: off        
      - IN: nginx_image_11
      - IN: random_3

  - name: runSh_main_2
    type: runSh
    dependencyMode: immediate
    steps:
      - IN: manifest_5
      - IN: sample_node_runCI
      - IN: runSh_trigger_2
      - IN: runSh_trigger_3
        switch: off
      - IN: manifest_6
      - IN: manifest_7
        switch: off           
      - IN: nginx_image_12
      - IN: random_4
      - TASK:
        - script: sleep 60
        
  - name: manifest_final
    type: manifest
    steps:
      - IN: sample_node_runCI
      - IN: runSh_trigger_2
      - IN: runSh_trigger_3
      
  - name: manifest_final_2
    type: manifest
    steps:
      - IN: random_5
      - IN: sample_node_runCI
      - IN: runSh_trigger_2
      - IN: runSh_trigger_3      

  - name: random_1
    type: runSh
    steps:
      - TASK:
        - script: sleep 300

  - name: random_2
    type: runSh
    steps:
      - TASK:
        - script: sleep 240

  - name: random_3
    type: runSh
    steps:
      - TASK:
        - script: sleep 180

  - name: random_4
    type: runSh
    steps:
      - TASK:
        - script: sleep 120

  - name: random_5
    type: runSh
    steps:
      - TASK:
        - script: sleep 60 

resources:
  - name: nginx_image_10
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.10
      
  - name: nginx_image_11
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.11
      
  - name: nginx_image_12
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.12
