jobs:
  - name: nginx-manifest-3
    type: manifest
    steps:
      - IN: nginx-image-3
      - TASK: managed

#  - name: triton-deploy-3
#    type: deploy
#    steps:
#      - IN: nginx-manifest-3
#      - IN: triton-cluster-3
#      - TASK: managed
