jobs:
  - name: runSh_1_n
    type: runSh
    steps:
      - TASK:
        - script: secs=6; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done

  - name: runSh_2_n
    type: runSh
    steps:
      - IN: runSh_1_n
      - TASK:
        - script: secs=6; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done

  - name: runSh_3_n
    type: runSh
    steps:
      - IN: runSh_1_n
      - TASK:
        - script: secs=6; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done

  - name: runSh_4_n
    type: runSh
    steps:
      - IN: runSh_1_n    
      - TASK:
        - script: secs=6; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
