jobs:
  - name: man-prod9
    type: manifest
    steps:
      - IN: nginx-prod9
      - TASK: managed

  - name: man-prod10
    type: manifest
    steps:
      - IN: nginx-prod10
      - IN: replicas
      - IN: params
      - IN: dockerOptions      
      - TASK: managed

  - name: azure
    type: deploy
    steps:
      - IN: man-prod9   
      - IN: man-prod10
        switch: off
      - IN: azure-cluster
      - TASK: managed
        deployMethod: blueGreen
    flags:
      - azure

resources:
  - name: nginx-prod10
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.10

  - name: nginx-prod9
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.9

  - name: replicas
    type: replicas
    version:
      count: 1

  - name: params
    type: params
    version:
      params:
        API_URL: https://localhost:3000
        WWW_URL: https://localhost:8080

  - name: dockerOptions
    type: dockerOptions
    version:
      portMappings:
        - "80:80/tcp"

  - name: azure-cluster
    type: cluster
    integration: azure-subint  
