jobs:
  - name: nginx-manifest-1
    type: manifest
    triggerMode: not-parallel    
    steps:
      - IN: serial-trigger
    flags:
      - manifests 

  - name: runSh-Job
    type: runSh
    triggerMode: parallel    
    steps:
      - IN: nginx-manifest-1
      - TASK:
        - script: sudo apt-get install tree
        - script: tree -F IN
        - script: sleep 3
        - script: echo "hello"
    on_success:
      - script: echo "successfully completed"
      
  - name: runSh-Job-N
    type: runSh 
    steps:
      - IN: nginx-manifest-1
      - TASK:
        - script: sudo apt-get install tree
        - script: tree -F IN
        - script: sleep 3       
    on_success:
      - script: echo "successfully completed"      

  - name: runSh-Job-2
    type: runSh
    triggerMode: parallel
    steps:
      - IN: nginx-manifest-1
      - TASK:
        - script: sudo apt-get install tree
        - script: tree -F IN
        - script: sleep 30
    on_success:
      - script: echo "successfully completed"      
